max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_field_init_shorthand = true
wrap_comments = true
format_strings = true
use_try_shorthand = false
force_explicit_abi = true
