[package]
name = "common-port-forward"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
console-subscriber = "0.2"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["json"] }
tracing-appender = "0.2"
lazy_static = "1.4"
tokio = { version = "1.38", features = ["full", "tracing"] }
